name: My Custom CSharp Action
description: I am an example of a container action that uses CSharp
inputs:
  name:
    description: a name
    required: true
    default: Elvis
  whatilike:
    description: something i like
    required: true
    default: kittens
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.name }}
    - ${{ inputs.whatilike }}