name: My Custom CSharp Action
description: I am an example of a container action that uses CSharp
inputs:
  name:
    description: a name
    required: true
    default: Elvis
outputs:
  dad-joke:
    description: The Dad Joke
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.name }}