name: Build and Test GitHub actions
on:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and test the GitHub Action
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Run the private action
      id: csharp
      uses: ./
      with:
        name: MickeyG

    - name: Output Dad Joke
      run: echo "${{ steps.csharp.outputs.dad-joke }}"
      
    - uses: mickeygoussetorg/my-custom-csharp-container-action@main
      id: dadjoke2
      with:
        name: MickeyG2
        
    - name: Output Dad Joke 2
      run: echo "${{ steps.dadjoke2.outputs.dad-joke }}"
