name: Build and Test GitHub actions
on:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and test the GitHub Action
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Run the private action
      id: csharp
      uses: ./
      with:
        name: MickeyG
        whatilike: cabbages

    - name: Did I Get Output
      run: echo "please work = ${{ steps.csharp.outputs.pleasework }}"

    - name: Output Dad Joke
      run: echo "${{ steps.csharp.outputs.dad-joke }}"